// Auto-generated by generate-web-examples — do not edit.

export const EXAMPLES = {
  simple: {
    label: "Key/value config",
    description: "Comments, whitespace, identifiers, and SOI/EOI.",
    entryRule: "main",
    pest: `// Key/value config example.
// Comments, whitespace, identifiers, and SOI/EOI.
// Entry rule: main
// Try: a=1,b=2, x=9 // comment\\n,y=8
WHITESPACE = _{ " " | "\\t" | newline }
COMMENT = _{ line_comment }
newline = _{ "\\n" | "\\r\\n" }
line_comment = _{ "//" ~ (!newline ~ ANY)* }

main = { SOI ~ item ~ ("," ~ item)* ~ EOI }
item = { #name = ident ~ "=" ~ #value = number }
ident = @{ ("_" | ASCII_ALPHA) ~ ("_" | ASCII_ALPHANUMERIC)* }
number = @{ ASCII_DIGIT+ }
`,
  },
  calc: {
    label: "Calculator",
    description: "Arithmetic with precedence and recursion.",
    entryRule: "expr",
    pest: `// Calculator example.
// Arithmetic with precedence and recursion.
// Entry rule: expr
// Try: 1 + 2 * 3, (1 + 2) * 3
expr = { term ~ ( #op = ("+" | "-") ~ term )* }
term = { factor ~ ( #op = ("*" | "/") ~ factor )* }
factor = { #inner = number | "(" ~ #inner = expr ~ ")" }
number = @{ ASCII_DIGIT+ }
WHITESPACE = _{ " " | "\\t" }
`,
  },
  ranges: {
    label: "Hex color",
    description: "Character ranges like '0'..'9' and bounded repetition.",
    entryRule: "main",
    pest: `// Hex color example.
// Character ranges like '0'..'9' and bounded repetition.
// Entry rule: main
// Try: #ff00aa, #AABBCC
WHITESPACE = _{ " " }
main = { SOI ~ hex_color ~ EOI }
hex_color = { "#" ~ #body = hex_digit{6} }
hex_digit = _{ '0'..'9' | 'a'..'f' | 'A'..'F' }
`,
  },
  case_insensitive: {
    label: "SQL-ish query",
    description: "Case-insensitive string literals with ^\"select\".",
    entryRule: "main",
    pest: `// SQL-ish query example.
// Case-insensitive string literals with ^"select".
// Entry rule: main
// Try: select from foo, SELECT FROM bar
WHITESPACE = _{ " " }
main = { SOI ~ #select = ^"select" ~ #from = ^"from" ~ #table = ident ~ EOI }
ident = @{ ("_" | ASCII_ALPHA) ~ ("_" | ASCII_ALPHANUMERIC)* }
`,
  },
  lookahead: {
    label: "Lookahead sentinel",
    description: "Negative lookahead !\"end\" before a closing sentinel.",
    entryRule: "main",
    pest: `// Lookahead sentinel example.
// Negative lookahead !"end" before a closing sentinel.
// Entry rule: main
// Try: hello world end, foo_bar end
WHITESPACE = _{ " " }
main = { SOI ~ #id = ident ~ #prefix = (!"end" ~ ANY)* ~ "end" ~ EOI }
ident = @{ ("_" | ASCII_ALPHA) ~ ("_" | ASCII_ALPHANUMERIC)* }
`,
  },
};

export const DEFAULT_EXAMPLE_KEY = "simple";
export const DEFAULT_PEST = EXAMPLES[DEFAULT_EXAMPLE_KEY].pest;
